### ISSUE TITLE
Icon gets cut off on custom Shell Theme

### ISSUE THREAD

**Issue by Null-Senpai** [Exalm/gnome-shell-extension-dynamic-battery#3] opened 2017-07-23 11:04 UTC
The icon get's cut off when using a custom GNOME Shell theme.
It works fine on the default Adwaita.

GNOME Shell: 3.24.3
Shell Theme: Arc

Image of issue:
![bar](https://user-images.githubusercontent.com/13616397/28498822-f12eb2cc-6f9e-11e7-87ec-a8585182fa87.png)

**Comment by Exalm** [comment] 2017-07-23 11:07
Oh, thanks. I thought I fixed all such bugs. I'll look into it a bit later
:)

23 июл. 2017 г. 16:04 пользователь "null" <notifications@github.com>
написал:

**Comment by Exalm** [comment] 2017-07-23 15:40
Confirmed.

**Comment by Exalm** [comment] 2017-07-23 15:43
Additionally, text in the aggregate system menu is misaligned.

**Comment by Exalm** [comment] 2017-07-23 16:02
Ok, I see. The problem is that Arc theme uses a smaller font (9 instead of 11) and the icon size is in px, while it's in em in the extension.
This actually might be worth fixing in Arc itself, because it means that it wouldn't scale on hi-dpi.
However, this also means that I should determine the icon size in runtime instead of hardcoding it in CSS.

**Comment by Exalm** [comment] 2017-07-23 17:10
Thanks again, it's fixed now. I don't know how much time it'll take to appear on extensions.gnome.org, but you can install it from here right now. :)

**Comment by Exalm** [comment] 2017-07-23 17:12
Wait a minute. I made a mistake

**Comment by Exalm** [comment] 2017-07-23 17:15
Ok, I made a typo. Now it's really fixed :)

**Closed** 2017-07-23 17:15 UTC

**Comment by Exalm** [comment] 2017-07-24 10:56
The fix is live on extensions.gnome.org now.

**Comment by Null-Senpai** [comment] 2017-07-24 13:58
Oh wow, what was fast. Thanks a lot!
