### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by medicamin** [Exalm/gnome-shell-extension-dynamic-battery#2] opened 2017-07-01 05:41 UTC
Hi there,
I just wanted to inform you about an AUR package which on of my friends has build it yesterday:

gnome-shell-extension-dynamic-battery-git

Now Arch users can easily install this great extension via AUR.

good work. keep updating...

**Comment by Exalm** [comment] 2017-07-01 07:41
Ok. So, can I close it, it so you want me to add the pkgbuild into the repo? :)

**Comment by medicamin** [comment] 2017-07-01 07:56
yes, close it. I just wanted to inform you.
If you could, please add this extension to Gnome extension website.

**Comment by Exalm** [comment] 2017-07-01 07:59
Ah, I was going to do that, but I wasn't sure about licensing (because the icons are from different projects, not all of which are GPL2+, but some, for example, are GPL3. And I wanted to fix #1 first, but I can't reproduce it on F26 anymore.

**Comment by medicamin** [comment] 2017-07-01 08:07
I think it's not necessary to include several icon types. Or you may provide an option to let users add their own icons. these downloadable icons can be on your github account, and users may download them by selecting them on the settings page. 

About the issue you mentioned, if you make this extension more public, more people can participate in bug reporting.

**Comment by Exalm** [comment] 2017-07-01 08:19
The thing is that you can't just add your own icons, because you have to modify them and write some rules so it looks good. If you are able to do that, it's all good, but most people aren't.
But yes, I agree that it needs to be on extensions.gnome.org.

**Comment by Exalm** [comment] 2017-07-01 08:23
And yes, it's not like the extensions.gnome.org people told me that I cannot do that, it's that I wasn't sure, so maybe that's not a problem at all.

**Comment by Exalm** [comment] 2017-07-09 08:57
I've just proposed it to extensions.gnome.org again, so maybe it'll be there. :)

**Comment by Exalm** [comment] 2017-07-11 09:23
Ok, it's there. :)
https://extensions.gnome.org/extension/1213/dynamic-battery/
Closing.

**Closed by Exalm** 2017-07-11 09:23 UTC
